server:
  port: 8080
  include: swagger

spring:
  datasource:
    url: jdbc:mysql://10.10.1.35:3306/rpm_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    password: 123
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 1000
    #redis数据库索引，默认0
    database: 1
    jedis:
      pool:
        #连接池最大连接数
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0


mybatis:
  mapper-locations: classpath*:dao/*.xml
  type-aliases-package: cn.com.dhc.rpmsystem.entity
