server:
  port: 8666
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rpm_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
